#!/bin/bash
export NEWT_COLORS='root=,black
border=green,black
title=green,black
roottext=red,black
window=red,black
textbox=white,black
button=black,green
compactbutton=white,black
listbox=white,black
actlistbox=black,white
actsellistbox=black,green
checkbox=green,black
actcheckbox=black,green
'
title="What Station do you want to listen to?"
msgbox_height=20
msgbox_width=60
export GPG_TTY=$(tty)
unset DISPLAY
# Accounts (If Multiple)
comedy="user = EMAIL_ACCOUNT_1"
music="user = EMAIL_ACCOUNT_2"
password="password_command = gpg2 --decrypt ~/.config/pianobar/password"

#Get your station ID from pianobar or you can also attain them on Pandora.com
station1="autostart_station = AUTOSTART_STATION_ID1" # Comedy Station
station2="autostart_station = AUTOSTART_STATION_ID2" # Quick Mix Station
station3="autostart_station = AUTOSTART_STATION_ID3" # Motown Station
station4="autostart_station = AUTOSTART_STATION_ID4" # SRV Station
station5="autostart_station = AUTOSTART_STATION_ID5" # Rock Mix Station
station6="autostart_station = AUTOSTART_STATION_ID6" # 90s Pop Station
station7="autostart_station = AUTOSTART_STATION_ID7" # Genre Hop Station
#Song Format
song="format_nowplaying_song = [1;4m[1;96m%t[m  ☠  [1;4m%a[m ☠  [1;4m[1;33m%l [m%r [m"
playing="format_nowplaying_station = [1;4mNow Playing[m [1;4m[1;94m%n[m [1;4m[1;31m(%i) [m [1;4m[1;35m"
format="format_list_song = %i)  [m[1;4m[1;96m%t[m - [1;4m%a[m [1;32m%r [m"
time_format="format_time = [1;4m[1;4m%e[m/[1;4m[1;31m%t [m"
FMI='format_msg_info = [1;4m[1;33m(i)[m %s'
FMN='format_msg_nowplaying = [1;4m[1;4m|>[m %s'
FMT='format_msg_time = [1;4m[1;33m#[m %s'
FME='format_msg_err = [1;4m[1;33m/!\[m %s'
FMQ='format_msg_question = [1;4m[1;4m[?][m %s'
# If you dont have a ctl file Run : and run mkfifo ~/.config/pianobar/ctl
pipe="fifo = ~/.config/pianobar/ctl"
songlist="history = 25"
calc_wt_size() {
    ##WT_WIDTH=$(tput cols)
	# Bash knows the terminal size
	# echo "The number of columns are $COLUMNS"
	# echo "The number of lines are $LINES"

    if [ $LINES -lt 14 ]; then
    	echo "Terminal size must be at least 22 lines."
    	exit
    fi
    if [ $COLUMNS -lt 30 ]; then
    	echo "Terminal size must be at least 60 columns."
    	exit
    fi

    WT_HEIGHT=32

    # Leave full width up to 100 columns
    WT_WIDTH=$COLUMNS
    if [ $COLUMNS -gt 40 ]; then
    	WT_WIDTH=40
    fi

    WT_MENU_HEIGHT=$(($WT_HEIGHT - 8))
}

pe ()
{
# Passphrase encryption program
# Created by Dave Crouse 01-13-2006
# Reads input from text editor and encrypts to screen.
# Adapted for Pianobar to Dynamically create encrypted password for pianobar
clear
echo "         Password Encryption For Pianobar";
echo "--------------------------------------------------"; echo "";
which $EDITOR &>/dev/null
 if [ $? != "0" ];
     then
     echo "It appears that you do not have a text editor set in your
.bashrc file.";
     echo "What editor would you like to use ? " ;
     read EDITOR ; echo "";
 fi
$EDITOR pandorapassword
gpg2 --armor --comment "$comment" --no-options --output pandorapassword.gpg --symmetric pandorapassword
shred -u pandorapassword ; clear
cat pandorapassword.gpg > ~/.config/pianobar/password
shred -u pandorapassword.gpg ;
clear
}

clear
if [ "$1" == "--help" ] ; then
        echo ""
        echo ""
        echo ""
        echo "          Usage: $ [1mpandora[m"
        echo "          What Station would you like to listen to?"
        echo "          1) [1;4m[1;32m90s Hits[m: [1;4m[1;31mtype[m [1;4m[1;33m1[m or [1;4m[1;33m90s[m"
        echo "          2) [1;4m[1;32mComedy[m: [1;4m[1;31mtype[m [1;4m[1;33m2[m, [1;4m[1;33mcomedy[m or [1;4m[1;33mComedy[m"
        echo "          3) [1;4m[1;32mGenre Hop[m: [1;4m[1;31mtype[m [1;4m[1;33m3[m, [1;4m[1;33mhop[m or [1;4m[1;33mgenremix[m"
        echo "          4) [1;4m[1;32mMotown[m: [1;4m[1;31mtype[m [1;4m[1;33m4[m, [1;4m[1;33mmotown[m or [1;4m[1;33mMotown[m"
        echo "          5) [1;4m[1;32mQuickMix[m: [1;4m[1;31mtype[m [1;4m[1;33m5[m, [1;4m[1;33mquickmix[m or [1;4m[1;33mQuickmix[m"
        echo "          6) [1;4m[1;32mRock Hits[m: [1;4m[1;31mtype[m [1;4m[1;33m6[m, [1;4m[1;33mrock[m or [1;4m[1;33mRock[m"
        echo "          7) [1;4m[1;32mSRV[m: [1;4m[1;31mtype[m [1;4m[1;33m7[m, [1;4m[1;33msrv[m or [1;4m[1;33mSRV[m"
        echo "          x) [1;4m[1;32mexit[m: [1;4m[1;31mtype[m [1;4m[1;33mx[m, [1;4m[1;33mq[m, [1;4m[1;33mX[m or [1;4m[1;33mexit[m"
        echo "          Any other option will loop back to this menu"
        sleep 1
        exit;
fi
if [ ! -f ~/.config/pianobar/password ] ; then
        pe
fi
while true ; do
if [ "$1" == "--text" ] || [ "$1" == "-t" ] ; then
        while true; do
        calc_wt_size
        FUN=$(whiptail --menu "" --title "$title" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT --ok-button "Select" --cancel-button "Exit" \
            "1" "90s Station" \
            "2" "Comedy Station" \
            "3" "Genre Mix Station" \
            "4" "Motown Station" \
            "5" "Quickmix Station" \
            "6" "Rock Hits Station" \
            "7" "SRV Station" \
            3>&1 1>&2 2>&3)
        if [ $? -ne 0 ]; then
            exit
        else
            case "$FUN" in
            1)
                echo -e "$music\n$station6\n$password\n$script\n$song\n$playing\n$format\n$pipe\n$songlist\n$FMI\n$FMN\n$FMT\n$FME\n$FMQ" > ~/.config/pianobar/config
                pianobar
                exit
                    ;;
            2)
                echo -e "$comedy\n$station1\n$password\n$script\n$song\n$playing\n$format\n$pipe\n$songlist\n$FMI\n$FMN\n$FMT\n$FME\n$FMQ" > ~/.config/pianobar/config
                pianobar
                exit
                    ;;

            3)
                echo -e "$music\n$station7\n$password\n$script\n$song\n$playing\n$format\n$pipe\n$songlist\n$FMI\n$FMN\n$FMT\n$FME\n$FMQ" > ~/.config/pianobar/config
                pianobar
                exit
                    ;;
            4)
                echo -e "$music\n$station3\n$password\n$script\n$song\n$playing\n$format\n$pipe\n$songlist\n$FMI\n$FMN\n$FMT\n$FME\n$FMQ" > ~/.config/pianobar/config
                pianobar
                exit
                    ;;
            5)
                echo -e "$music\n$station2\n$password\n$script\n$song\n$playing\n$format\n$pipe\n$songlist\n$FMI\n$FMN\n$FMT\n$FME\n$FMQ" > ~/.config/pianobar/config
                pianobar
                exit
                    ;;
            6)
                echo -e "$music\n$station5\n$password\n$script\n$song\n$playing\n$format\n$pipe\n$songlist\n$FMI\n$FMN\n$FMT\n$FME\n$FMQ" > ~/.config/pianobar/config
                pianobar
                exit
                    ;;
            7)
                echo -e "$music\n$station4\n$password\n$script\n$song\n$playing\n$format\n$pipe\n$songlist\n$FMI\n$FMN\n$FMT\n$FME\n$FMQ" > ~/.config/pianobar/config
                pianobar
                exit
                ;;
            *) whiptail --msgbox "Whoooops, script error: unrecognized option" $msgbox_height $msgbox_width ;;
            esac
        fi
    done
else

        echo "        [4m What Station would you like to listen to?[m"
        echo ""
        echo "          1) [1;4m[1;32m90s Hits[m: [1;4m[1;31mtype[m [1;4m[1;33m1[m or [1;4m[1;33m90s[m"
        echo "          2) [1;4m[1;32mComedy[m: [1;4m[1;31mtype[m [1;4m[1;33m2[m, [1;4m[1;33mcomedy[m or [1;4m[1;33mComedy[m"
        echo "          3) [1;4m[1;32mGenre Hop[m: [1;4m[1;31mtype[m [1;4m[1;33m3[m, [1;4m[1;33mhop[m or [1;4m[1;33mgenremix[m"
        echo "          4) [1;4m[1;32mMotown[m: [1;4m[1;31mtype[m [1;4m[1;33m4[m, [1;4m[1;33mmotown[m or [1;4m[1;33mMotown[m"
        echo "          5) [1;4m[1;32mQuickMix[m: [1;4m[1;31mtype[m [1;4m[1;33m5[m, [1;4m[1;33mquickmix[m or [1;4m[1;33mQuickmix[m"
        echo "          6) [1;4m[1;32mRock Hits[m: [1;4m[1;31mtype[m [1;4m[1;33m6[m, [1;4m[1;33mrock[m or [1;4m[1;33mRock[m"
        echo "          7) [1;4m[1;32mSRV[m: [1;4m[1;31mtype[m [1;4m[1;33m7[m, [1;4m[1;33msrv[m or [1;4m[1;33mSRV[m"
        echo "          x) [1;4m[1;32mexit[m: [1;4m[1;31mtype[m [1;4m[1;33mx[m, [1;4m[1;33mq[m, [1;4m[1;33mX[m or [1;4m[1;33mexit[m"
        echo ""
	read -p "Enter your choice: " CHOICE
    case "$CHOICE" in
		1|90s)
            echo -e "$music\n$station6\n$password\n$script\n$song\n$playing\n$format\n$pipe\n$songlist\n$FMI\n$FMN\n$FMT\n$FME\n$FMQ" > ~/.config/pianobar/config
            clear
            pianobar
            exit
			;;
		2|comedy|Comedy)
			echo -e "$comedy\n$station1\n$password\n$script\n$song\n$playing\n$format\n$pipe\n$songlist\n$FMI\n$FMN\n$FMT\n$FME\n$FMQ" > ~/.config/pianobar/config
            clear
            pianobar
            exit
			;;
        3|hop|genremix)
			echo -e "$music\n$station7\n$password\n$script\n$song\n$playing\n$format\n$pipe\n$songlist\n$FMI\n$FMN\n$FMT\n$FME\n$FMQ" > ~/.config/pianobar/config
            clear
            pianobar
            exit
			;;
		4|motown|Motown)
			echo -e "$music\n$station3\n$password\n$script\n$song\n$playing\n$format\n$pipe\n$songlist\n$FMI\n$FMN\n$FMT\n$FME\n$FMQ" > ~/.config/pianobar/config
            clear
            pianobar
            exit
			;;
		5|mix|quickmix|Quickmix)
            echo -e "$music\n$station2\n$password\n$script\n$song\n$playing\n$format\n$pipe\n$songlist\n$FMI\n$FMN\n$FMT\n$FME\n$FMQ" > ~/.config/pianobar/config
            clear
            pianobar
            exit
			;;
		6|rock|Rock)
			echo -e "$music\n$station5\n$password\n$script\n$song\n$playing\n$format\n$pipe\n$songlist\n$FMI\n$FMN\n$FMT\n$FME\n$FMQ" > ~/.config/pianobar/config
            clear
            pianobar
            exit
			;;
        7|srv|SRV)
			echo -e "$music\n$station4\n$password\n$script\n$song\n$playing\n$format\n$pipe\n$songlist\n$FMI\n$FMN\n$FMT\n$FME\n$FMQ" > ~/.config/pianobar/config
            clear
            pianobar
            exit
			;;
		x|X|exit|q)
            clear
			echo "Thanks for Listening... Goodbye"
			exit
			;;
		*)
			echo "Invalid choice! Try again."
			;;
	esac
fi
done
